services:
  postgres:
    image: postgres:16beta2-alpine
    restart: always
    environment:
      - POSTGRES_USER=$DBUSER
      - POSTGRES_PASSWORD=$DBPASS
      - POSTGRES_DB=$DBNAME
      - PORT=$PORT
    #    ports:
    #      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $DBNAME']
      interval: 10s
      timeout: 5s
      retries: 5
  buntes:
    build: .
    ports:
      - '$PORT:$PORT'
    environment:
      - DBUSER=$DBUSER
      - DBPASS=$DBPASS
      - DBNAME=$DBNAME
      - PORT=$PORT
      - HOST=$HOST
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
#  prometheus:
#    image: prom/prometheus:latest
#    volumes:
#      - ./monitoring/:/etc/prometheus/
#    ports:
#      - 9090:9090
#    links:
#      - buntes
#  grafana:
#    image: grafana/grafana:latest
#    volumes:
#      - ./monitoring/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
#    ports:
#      - 3001:3000
#    environment:
#      - GF_AUTH_DISABLE_LOGIN_FORM=true
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    links:
#      - prometheus
volumes:
  db:
    driver: local
